# Site settings
title: Pedro Pinhal Actor
email: pedro.pinhal@gmail.com
url: http://www.pedropinhal.com
description: "Pedro Pinhal Actor website. View my reel, credits, training and blog."
baseurl:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Pedro Pinhal

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/PedroPinhal
  - title: spotlight
    icon: star-o
    url: http://www.spotlight.com/interactive/cv/8014-6727-0395
  - title: casting call pro
    icon: copyright
    url: http://www.uk.castingcallpro.com/view.php?uid=224077
  - title: imdb
    icon: info
    url: http://www.imdb.com/name/nm3155663/

# Build settings
markdown: kramdown
permalink: pretty
